#+TITLE: CV
#+AUTHOR: Tiitus Järvinen

* Tietoja
  Olen 1. vuoden kandidaattiopiskelija Aalto-yliopistossa. Pääaineeni on tietotekniikka.
  
* Työkokemus

** Puolustusvoimat - Ohjelmoija
   Toimipaikka: Jääkäriprikaati, Rovaniemi.
   
   Aika: 30.08.2019 - 18.03.2020
   
   Puolustusvoimien VBS 3 FDF-taistelusimulaattorin kehitystä sekä simulaattoriympäristön ylläpitoa ja käyttöä. Toimin menestyksekkäästi viiden kehittäjän ryhmän johtajana, ja sain työstäni korpraalin arvon ja kunniakirjan. 

   Lisätietoja: Vääpeli Joonas Mourujärvi, +358 40 0261395
   
** Haapaveden kaupunki - Ruohonleikkaaja
   Toimipaikka: Haapavesi.
   
   Aika: Kesäkuu 2019
   
** Haapaveden kaupunki - Ruohonleikkaaja
   Toimipaikka: Haapavesi.
   
   Aika: Kesäkuu 2016

** Raution tila - Kaalinistuttaja
   Toimipaikka: Haapavesi
   
   Aika: Kesäkuu 2015
   
   Lisätietoja: 0405200253
   
* Taidot

** Ohjelmointikielet
   - Kotlin (Kattava)
   - Dart (Flutter) (Erinomainen)
   - Scala (Erinomainen)
   - Java (Hyvä)
   - Python (Hyvä)
   - HTML, CSS, Bootstrap jne. (Hyvä)
   - Typescript / Javascript (Melko hyvä)
   - SQL (Melko hyvä)
   - Go (Melko hyvä)

** Ohjelmistot
   - Linux
   - Git
   - Adobe-perheen yleisimmät ohjelmistot, erityisesti Photoshop, After Effects, XD, Illustrator ja Premiere Pro.
   - Microsoft Office-perheen ohjelmistot
   - Affinity Designer
   - Android Studio/Intellij IDEA

** Kielet
   - Suomi (Äidinkieli)
   - Englanti (Erinomainen puhe ja kirjoitus)
   - Ruotsi (Kirjoitustaito kohtalainen, puhetaito välttävä)
   - Ranska (Kirjoitustaito kohtalainen, puhetaito välttävä)

** Muut taidot
   Yleinen osaaminen tietokoneiden kasaamisesta, ylläpidosta ja käytöstä. Olen kasannut koneita ja kotiservereitä jo pienestä pitäen.

   Olen käyttänyt Linuxia päivittäin Windowssin ohella jo vuosia, ja kykenen työskentelemään terminaaliympäristössä sujuvasti.

   Minulla on myös runsaasti kokemusta versionhallinnasta; olen käyttänyt Git-järjestelmää sekä omien projektieni hallintaan että suuremmissa tiimityöskentely-ympäristöissä.
   Hallitsen myös useimmat videoeditointiohjelmat, ja tein lukioaikoinani lukuisia koosteita koululleni.

* Koulutus
  Olen tällä hetkellä opiskelija Aalto-Yliopistossa, ja pääaineeni on tietotekniikka.
** Ylioppilas - Haapaveden Lukio (Valm. Kevät 2019)

*** YO-Kokeiden tulokset
    | Englanti             | L |
    | Äidinkieli           | L |
    | Matematiikka (Pitkä) | E |
    | Kemia                | E |
    | Fysiikka             | E |
    | Ruotsi               | C |


    Hygieniapassi

* Lisätietoja ja linkkejä:
  Toimin osana Haapaveden lukion Tietotekniikka-tukitiimiä, joka oli vastuussa lukioaikanani muiden oppilaiden ja opettajien avustuksesta, sekä tietotekniikkaympäristöjen asennuksesta ja ylläpidosta.
  [[https://www.github.com/tipej][GitHub]]

  
